from pyspark.sql.types import StructType,StructField,LongType,StringType

userBadges_schema=StructType(
    [
        StructField("Id",LongType(),nullable=True),
        StructField("UserId",LongType(),nullable=True),
        StructField("Name",StringType(),nullable=True),
        StructField("AboutMe",StringType(),nullable=True),
        StructField("DisplayName",StringType(),nullable=True),
        StructField("DownVotes",LongType(),nullable=True),
        StructField("LastAccessDate",StringType(),nullable=True),
        StructField("Location",StringType(),nullable=True),
        StructField("ProfileImageUrl",StringType(),nullable=True),
        StructField("Reputation",LongType(),nullable=True),
        StructField("UpVotes",LongType(),nullable=True),
        StructField("WebsiteUrl",StringType(),nullable=True)
    ]
)

userPosts_schema=StructType(
    [
        StructField("Id",LongType(),nullable=True),
        StructField("DisplayName",StringType(),nullable=True),
        StructField("DownVotes",LongType(),nullable=True),
        StructField("Location",LongType(),nullable=True),
        StructField("Reputation",LongType(),nullable=True),
        StructField("UpVotes",LongType(),nullable=True),
        StructField("UpVotes",LongType(),nullable=True),
        StructField("Views",LongType(),nullable=True),
        StructField("AcceptedAnswerId",LongType(),nullable=True),
        StructField("AnswerCount",LongType(),nullable=True),
        StructField("Body",StringType(),nullable=True),
        StructField("ClosedDate",StringType(),nullable=True),
        StructField("CommentCount",LongType(),nullable=True),
        StructField("CommunityOwnedDate",StringType(),nullable=True),
        StructField("FavoriteCount",LongType(),nullable=True),
        StructField("PostId",LongType(),nullable=True),
        StructField("LastActivityDate",StringType(),nullable=True),
        StructField("LastEditDate",StringType(),nullable=True),
        StructField("LastEditorDisplayName",StringType(),nullable=True),
        StructField("LastEditorUserId",LongType(),nullable=True),
        StructField("OwnerDisplayName",StringType(),nullable=True),
        StructField("OwnerUserId",LongType(),nullable=True),
        StructField("ParentId",LongType(),nullable=True),
        StructField("PostTypeId",LongType(),nullable=True),
        StructField("Score",LongType(),nullable=True),
        StructField("Tags",StringType(),nullable=True),
        StructField("Title",StringType(),nullable=True)
    ]
)

userCommentsVotes_schema=StructType(
    [
        StructField("Id",LongType(),nullable=True),
        StructField("UserId",LongType(),nullable=True),
        StructField("UserDisplayName",StringType(),nullable=True),
        StructField("PostId",LongType(),nullable=True),
        StructField("Text",StringType(),nullable=True),
        StructField("Score",LongType(),nullable=True),
        StructField("AboutMe",StringType(),nullable=True),
        StructField("AccountId",LongType(),nullable=True),
        StructField("DisplayName",StringType(),nullable=True),
        StructField("DownVotes",StringType(),nullable=True),
        StructField("LastAccessDate",StringType(),nullable=True),
        StructField("Location",StringType(),nullable=True),
        StructField("ProfileImageUrl",StringType(),nullable=True),
        StructField("Reputation",LongType(),nullable=True),
        StructField("UpVotes",LongType(),nullable=True),
        StructField("Views",LongType(),nullable=True),
        StructField("WebsiteUrl",StringType(),nullable=True)
    ]
)